sudo: required
#services:
#  - docker
language: python
# command to run tests
script:
  # unit test
#  - python -m pytest -v
  - pwd
  - ls
  - printenv
  - echo "this is a new line" >> test.txt
  # linting test
  # - flake8
after_success:
  - git add -A
  - git commit -m "Travis deploy"
  - git push