stages:
  - name: deploy
    if: sender != traviscibot AND sender != Travis AND sender != "tkdepend" AND sender != "jpardinas" 
sudo: required
#services:
#  - docker
language: python
install:
  - pip install -r requirements.txt
# command to run tests
script:
  # unit test
#  - python -m pytest -v
  - pwd
  - ls
  - cd qa && ls
  # linting test
  # - flake8
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $token  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  name: tkdepend
  target_branch: test-deply
  on:
    branch: test-deply
