sudo: required
stages:
  - name: deploy
    if: TRAVIS_COMMIT_MESSAGE != *"Deploy JPardinas"*
#services:
#  - docker
language: python
# command to run tests
script:
  # unit test
#  - python -m pytest -v
  - pwd
  - ls
  - printenv
  - echo "this is a new line" >> test.txt
  # linting test
  # - flake8
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $token  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  name: tkdepend
  target_branch: test-deply
  on:
    branch: test-deply